version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_test_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: testdb
      MYSQL_USER: testuser
      MYSQL_PASSWORD: testpass
    ports:
      - "3307:3306"
    volumes:
      - mysql-test-data:/var/lib/mysql

volumes:
  mysql-test-data:
